[package]
name = "remycord"
version = "0.0.1"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
crossterm = "0.29.0"
ratatui = "0.29.0"
chrono = "0.4.42"
serde = { version = "1.0", features = ["derive"] }
toml = "0.9.8"
dirs = "6.0.0"
unicode-width = "0.2"
serde_yaml = "0.9"
