title: remycord
description: A Discord TUI client built with Rust and Ratatui
baseurl: "/remycord"
url: "https://gideonmt.github.io"

markdown: kramdown

# Navigation
navigation:
  - title: Home
    url: /
  - title: Installation
    url: /installation/
  - title: Configuration
    url: /configuration/
  - title: Themes
    url: /configuration/themes
  - title: GitHub
    url: https://github.com/gideonmt/remycord
    external: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
